<a href="https://colab.research.google.com/github/ishaqafridi/pyMSA/blob/master/msaviz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install Bio

  Using cached bio-1.7.1-py3-none-any.whl (280 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 14.6 MB/s eta 0:00:00


In [6]:
from Bio import Entrez

In [12]:
sequence=Entrez.efetch(db='nucleotide',id='M28276.1',rettype='fasta')

/usr/local/lib/python3.10/dist-packages/Bio/Entrez/__init__.py:723: UserWarning: 
            Email address is not specified.

            To make use of NCBI's E-utilities, NCBI requires you to specify your
            email address with each request.  As an example, if your email address
            is A.N.Other@example.com, you can specify it as follows:
               from Bio import Entrez
               Entrez.email = 'A.N.Other@example.com'
            In case of excessive usage of the E-utilities, NCBI will attempt to contact
            a user at the email address provided before blocking access to the
            E-utilities.
  warnings.warn(


In [14]:
sequence.read()

'>M28276.1 Frog albumin mRNA, partial cds\nCACTGCTGTGCCGTACCTGAAAATCAAAGGATGCCATGTGCAGAAGGAGACCTTACCATTCTCATTGGAA\nAAATGTGTGAAAGGCAAAAGAAGACATTTATAAATAACCACGTTGCTCATTGCTGCACTGACTTATATTC\nTGGGATGCGTTCATGCTTTACTGCTCTTGGTCCAGATGAGGACTATGTACCACCCCCAGTTACTGATGAC\nACATTTGACTTTGACGACAAGATATGCACTGCTAATGATAAAGAAAAACAGCATATCAAACAGAAATTCC\nTTGTGAAGCTGATTAAA\n\n'

In [15]:
reference_sequence=Entrez.efetch(db='nucleotide',id='LN854577.1',rettype='fasta')

/usr/local/lib/python3.10/dist-packages/Bio/Entrez/__init__.py:723: UserWarning: 
            Email address is not specified.

            To make use of NCBI's E-utilities, NCBI requires you to specify your
            email address with each request.  As an example, if your email address
            is A.N.Other@example.com, you can specify it as follows:
               from Bio import Entrez
               Entrez.email = 'A.N.Other@example.com'
            In case of excessive usage of the E-utilities, NCBI will attempt to contact
            a user at the email address provided before blocking access to the
            E-utilities.
  warnings.warn(


In [16]:
reference_sequence.read()

'>LN854577.1 Sophora japonica partial pa1 gene for albumin 1 insecticidal protein\nTTGGCTCTTTTCTTGCTTGCCACATTCTTAATGTTCCCGACGAAGAAGGCAGAAGCAGCAGATTGTTCGG\nGTGCTTGTTCGCCATTTGAGATGCCACCATGCCGCTCTACCGACTGTCGCTGTATCCCCATTGTACTAGT\nTGGGGGTTTCTGTATATATCCAACTGGAACTGCATCTGTTATGAAGATAGTCGAGCAACATCCTAACTTA\nTGTGAGTCTCATGATGACTGCATGAAGAAGGGAAGTGGGAACTTCTGCGCTCCTTATTCTAATCCTTATA\nTCGATCACGGCTGGTGCTTA\n\n'

In [52]:
sequences=Entrez.efetch(db='nucleotide',id='LF853823.1,LF853819.1,HZ156110.1',rettype='fasta')

/usr/local/lib/python3.10/dist-packages/Bio/Entrez/__init__.py:723: UserWarning: 
            Email address is not specified.

            To make use of NCBI's E-utilities, NCBI requires you to specify your
            email address with each request.  As an example, if your email address
            is A.N.Other@example.com, you can specify it as follows:
               from Bio import Entrez
               Entrez.email = 'A.N.Other@example.com'
            In case of excessive usage of the E-utilities, NCBI will attempt to contact
            a user at the email address provided before blocking access to the
            E-utilities.
  warnings.warn(


In [18]:
sequences.read()

'>LF853823.1 JP 2015126746-A/172: Albumin Fusion Proteins\nATGTGCTGTACCAAGAGTTTGCTCCTGGCTGCTTTGATGTCAGTGCTGCTACTCCACCTCTGCGGCGAAT\nCAGAAGCAGCAAGCAACTTTGACTGCTGTCTTGGATACACAGACCGTATTCTTCATCCTAAATTTATTGT\nGGGCTTGACACGGCAGCTGGCCAATGAAGGCTGTGACATCAATGCTATCATCTTTCACACAAAGAAAAAG\nTTGTCTGTGTGCGCAAATCCAAAACAGACTTGGGTGAAATATATTGTGCGTCTCCTCAGTAAAAAAGTCA\nAGAACATGTAA\n\n>LF853819.1 JP 2015126746-A/168: Albumin Fusion Proteins\nATGTGCTGTACCAAGAGTTTGCTCCTGGCTGCTTTGATGTCAGTGCTGCTACTCCACCTCTGCGGCGAAT\nCAGAAGCAGCAAGCAACTTTGACTGCTGTCTTGGATACACAGACCGTATTCTTCATCCTAAATTTATTGT\nGGGCTTGACACGGCAGCTGGCCAATGAAGGCTGTGACATCAATGCTATCATCTTTCACACAAAGAAAAAG\nTTGTCTGTGTGCGCAAATCCAAAACAGACTTGGGTGAAATATATTGTGCGTCTCCTCAGTAAAAAAGTCA\nAGAACATGTAA\n\n>HZ156110.1 JP 2015120714-A/167: Albumin Fusion Proteins\nATGTGCTGTACCAAGAGTTTGCTCCTGGCTGCTTTGATGTCAGTGCTGCTACTCCACCTCTGCGGCGAAT\nCAGAAGCAGCAAGCAACTTTGACTGCTGTCTTGGATACACAGACCGTATTCTTCATCCTAAATTTATTGT\nGGGCTTCACACGGCAGCTGGCCAATGAAGGCTGTGACATCAATGCTATCATCTTTCACACAAAGAAAAAG\nTTG

In [22]:
# prompt: multiple alignment of sequences with different length

from Bio.Align import MultipleSeqAlignment
from Bio.Align import substitution_matrices
import numpy as np
from Bio import pairwise2
from Bio.Align import substitution_matrices
matrix = substitution_matrices.load("BLOSUM62")
blosum62 = np.asarray(matrix)
def convert_sequence_to_matrix(sequence, reference_sequence):
    seq_matrix = np.zeros((len(sequence), len(reference_sequence)))
    for i in range(len(sequence)):
        for j in range(len(reference_sequence)):
            seq_matrix[i, j] = blosum62[ord(sequence[i]) - ord('A'), ord(reference_sequence[j]) - ord('A')]
    return seq_matrix
def align_sequences(sequences):
    reference_sequence = max(sequences, key=len)
    for sequence in sequences:
        seq_matrix = convert_sequence_to_matrix(sequence, reference_sequence)
        print(seq_matrix)
        print(reference_sequence)
        alignments = pairwise2.align.localxx(seq_matrix, reference_sequence)
        for alignment in alignments:
            print(alignment)
# sequences = ["ACGT", "ACGTACGT", "ACGTACGTACGT"]
align_sequences(sequences)


[[ 4. -2. -1.  0.  4. -2. -1.  0.  4. -2. -1.  0.]
 [-2.  6.  0. -3. -2.  6.  0. -3. -2.  6.  0. -3.]
 [-1.  0.  5. -2. -1.  0.  5. -2. -1.  0.  5. -2.]
 [ 0. -3. -2.  4.  0. -3. -2.  4.  0. -3. -2.  4.]]
ACGTACGTACGT


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [24]:
from Bio import SeqIO

In [33]:
from Bio.Align.Applications.   .Align.Applications.MuscleCommandline as msc

ERROR: Could not find a version that satisfies the requirement Bio.Align.Applications.MuscleCommandline (from versions: none)
ERROR: No matching distribution found for Bio.Align.Applications.MuscleCommandline


In [35]:
pip install muscle

In [36]:
import os
os.environ['PATH'] += ':/path/to/muscle/executable'

In [37]:
muscle_cline = MuscleCommandline("muscle3.8.31_i86linux64", input=tmp.name)

In [41]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
from Bio.Align.Applications import MuscleCommandline
import os

# Define the sequences
seq1 = SeqRecord(Seq("ATCGATCG"), id="Seq1")
seq2 = SeqRecord(Seq("ATCGATAG"), id="Seq2")
seq3 = SeqRecord(Seq("ATCGATCA"), id="Seq3")

# Create a list of sequences
sequences = [seq1, seq2, seq3]

# Write the sequences to a temporary file
from tempfile import NamedTemporaryFile
with NamedTemporaryFile(mode='w', delete=False) as tmp:
    for seq in sequences:
        SeqIO.write(seq, tmp, "fasta")
    tmp.close()
    print("Temporary file:", tmp.name)

# Run Muscle to align the sequences
# muscle_cline = MuscleCommandline("muscle3.8.31_i86win32.exe", input=tmp.name)
print("Muscle command:", muscle_cline)
# stdout, stderr = muscle_cline()
# stdout, stderr = muscle_cline()

# Check if the output file exists
output_file = tmp.name + ".aln"
if not os.path.exists(output_file):
    print("Error: Output file does not exist:", output_file)
else:
    print("Output file exists:", output_file)

# Read the alignment from the output file
align = MultipleSeqAlignment([])
with open(output_file, "r") as f:
    for record in SeqIO.parse(f, "fasta"):
        align.append(record)

# Print the alignment
print(align)

Temporary file: /tmp/tmp_g52073k
Muscle command: muscle3.8.31_i86win32.exe -in /tmp/tmpv2ghkaqh
Error: Output file does not exist: /tmp/tmp_g52073k.aln


FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_g52073k.aln'

In [47]:
from Bio.AlignIO import ClustalIO

In [3]:
pip install Bio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.0/281.0 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 14.1 MB/s eta 0:00:00


In [4]:
from Bio import Entrez

In [33]:
seq1=Entrez.efetch(db='nucleotide',id='HZ156108.1',rettype='fasta')
seq2=Entrez.efetch(db='nucleotide',id='HZ156109.1',rettype='fasta')
seq3=Entrez.efetch(db='nucleotide',id='HZ156110.1',rettype='fasta')

In [34]:
se1=seq1.read()
se2=seq2.read()
se3=seq3.read()

In [21]:
pip install clustal

ERROR: Could not find a version that satisfies the requirement clustal (from versions: none)
ERROR: No matching distribution found for clustal


In [35]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import clustal
from Bio.AlignIO import ClustalIO
# Bio.Align import multiple_sequence_alignment

# Define the sequences
seq11 = SeqRecord(Seq(se1), id="Seq11")
seq22 = SeqRecord(Seq(se2), id="Seq22")
seq33 = SeqRecord(Seq(se3), id="Seq33")

# Create a list of sequences
# sequ =SeqRecord.seq(seq11,seq22,seq33)
sequences = [
    SeqRecord(Seq(se1), id="Seq11"),
    SeqRecord(Seq(se2), id="Seq22"),
    SeqRecord(Seq(se3), id="Seq33"),
]
# Print the sequences
# print(sequences)

# Align the sequences
align = ClustalIO.MultipleSeqAlignment(sequences)

# Print the alignment
print(align)

Alignment with 3 rows and 354 columns
>HZ156108.1 JP 2015120714-A/165: Albumin Fus...A

 Seq11
>HZ156109.1 JP 2015120714-A/166: Albumin Fus...A

 Seq22
>HZ156110.1 JP 2015120714-A/167: Albumin Fus...A

 Seq33


In [36]:
pip install pymsaviz

In [52]:
from pymsaviz import MsaViz, get_msa_testdata
# msa_file = get_msa_testdata("HIGD2A.fa")
msa_file = align
mv = MsaViz(msa_file, wrap_length=60, show_count=True)
ss=mv.savefig("api_example01.png")

In [50]:
msa_file = get_msa_testdata("MRGPRG.fa")
mv = MsaViz(msa_file, color_scheme="Taylor", wrap_length=80, show_grid=True, show_consensus=True)
mv.savefig("api_example02.png")

In [51]:
msa_file = get_msa_testdata("MRGPRG.fa")
mv = MsaViz(msa_file, end=180, wrap_length=60, show_consensus=True)
# Example: Extract MSA positions with less than 50% consensus identity
# Add markers and text annotations as needed
mv.savefig("api_example03.png")

AttributeError: 'MsaViz' object has no attribute 'get_msa_data'

In [40]:
mv

AttributeError: 'MsaViz' object has no attribute 'show'